site_name: MuCloud
pages:
- Introduction: 'index.md'
- Installing:
    - Install on Linux: 'install_linux.md'
    - Install on MacOSX: 'install_mac.md'
    - Install on Windows: 'install_windows.md'
    - Setting up AWS: 'setup_aws.md'
- Tutorial: 'tutorial.md'
- About:
    - License: 'license.md'
theme_dir: docs_theme
copyright: Copyright &copy; 2014-2015 Colin Jermain, Graham Rowlands